import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className="w-full max-h-screen h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-red-500">Hello this is name</div>
    </div>
  );
}
