import Head from "next/head";
import Image from "next/image";
import { NextPage } from "next";

import bg from "../public/bg.svg";
import InputField from "../components/ui/inputField";

const img = (
  <svg
    width="99"
    height="719"
    viewBox="0 0 99 719"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M16.3337 7.13968e-07L11.1757 30.5416C5.158 59.9924 -6.01769 119.985 5.15799 179.977C16.3337 239.97 50.7204 299.962 61.8961 361.045C73.0718 421.038 79.0895 481.03 61.8961 541.023C44.7027 601.015 22.3513 661.007 11.1757 690.458L-3.15159e-05 721L99 721L99 690.458C99 661.008 99 601.015 99 541.023C99 481.03 99 421.038 99 361.045C99 299.962 99 239.97 99 179.977C99 119.985 99 59.9925 99 30.5417L99 0.000114066L16.3337 7.13968e-07Z"
      fill="white"
    />
  </svg>
);

const Home: NextPage = () => {
  return (
    <div className="w-full max-h-screen h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;300;400;600;700;800;900&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <main className="flex-1 h-full flex flex-row">
        <div className="flex-1 relative flex justify-center items-center main-bg">
          <h1 className="text-white text-5xl uppercase font-black text-center leading-[54px] fade-in-right">
            KALKULATOR
            <br /> troška električne <br />
            energije
          </h1>
        </div>
        <div className="flex-1">
          <InputField label="Test one" name="test" valueType="kvarh" />
        </div>
      </main>
    </div>
  );
};

export default Home;
