import Head from "next/head";
import Image from "next/image";
import { NextPage } from "next";

import bg from "../public/bg.svg";

const Home: NextPage = () => {
  return (
    <div className="w-full max-h-screen h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex-1 h-full flex flex-row">
        <div className="flex-1 relative">
          <div>TITLTE</div>
        </div>
        <div className="flex-1">RIGHT SIDE</div>
      </main>
    </div>
  );
};

export default Home;
